version: '3.9'
name: streamlit-ollama
services:
  streamlit:
    image: python:3.9-slim
    ports:
      - '8501:8501'
    volumes:
      - ./app:/app
      - python-deps:/root/.cache/pip
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && streamlit run app.py"
    restart: unless-stopped

volumes:
  python-deps: {}